vich_uploader:
    db_driver: orm

    mappings:
       user_logo:
           uri_prefix: /images/user_logo
           upload_destination: '%kernel.project_dir%/public/images/user_logo'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true
